[symfony/framework-bundle/7.0 & 7.2] Add imports for services.yaml wi…
symfony/recipes pull request #1333
Opened 2024-08-19 15:50 UTC by Arkemlar

…th some comments for clarification

| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | .

This is tiny change for `config/services.yaml` file. I lost hours trying to understand how to use multiple service files correctly and everything I needed to know is the import order. Now it sounds obvious for me, but lots of stackoverflow questions shows that I am not the only one stuck on that. So I added some comments for imports statement to services.yaml. Hope it helps others to save time.

2024-09-14 20:19 UTC, Arkemlar commented
Hmm, can someone review and approve please?

2024-10-08 14:04 UTC, 94noni commented
what about add this in the doc instead ? could be more valuable (if not already done, or written differently )

2024-12-02 11:57 UTC, Arkemlar commented
@94noni I think, there are lower chances to miss it if we place it in file.

2024-12-02 12:05 UTC, Arkemlar commented
@nicolas-grekas @stof guys, could you please review this PR and approve if it's fine?

2024-12-04 06:10 UTC, fabpot requested changes

2024-12-04 06:10 UTC, fabpot commented on symfony/framework-bundle/7.0/config/services.yaml
> +# There comes imported service files, if you would like to split config to multiple files.
```suggestion
# Import additional files that should be processed before this file.
```

2024-12-04 06:10 UTC, fabpot commented on symfony/framework-bundle/7.0/config/services.yaml
> +# Duplicating services will be overridden and last config wins.
Let's remove these two lines as one can read the docs at this point.

2025-11-04 08:57 UTC, nicolas-grekas commented
I'm proposing https://github.com/symfony/recipes/pull/1466 instead. Thanks for suggesting.

2025-11-04 08:57 UTC, closed without merging