Add gatewayapi-notifier recipe
symfony/recipes pull request #835
Opened 2020-10-23 08:56 UTC by PGLongo

| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | [symfony/symfony-docs/pull/14463](https://github.com/symfony/symfony-docs/pull/14463)

Add recipe to use with GatewayAPI notifier [symfony/symfony/pull/38685](https://github.com/symfony/symfony/pull/38685)

2020-12-13 17:57 UTC, OskarStark requested changes

2020-12-13 17:57 UTC, OskarStark commented on symfony/gatewayapi-notifier/5.2/manifest.json
> +        "#1": "GATEWAYAPI_DSN=gatewayapi://AUTH_TOKEN@default?from=SENDER"
```suggestion
        "#1": "GATEWAYAPI_DSN=gatewayapi://TOKEN@default?from=SENDER"
```

2020-12-14 09:35 UTC, OskarStark commented
This should be moved to folder `5.3`

2020-12-14 11:19 UTC, PGLongo commented
@OskarStark I've moved the recipe.

2020-12-14 11:21 UTC, OskarStark approved these changes

2021-01-15 06:26 UTC, fabpot approved these changes

2021-01-15 06:26 UTC, fabpot commented
@symfony-flex-server review again please

2021-01-15 06:34 UTC, fabpot commented
@symfony-flex-server review again please

2021-01-15 06:36 UTC, fabpot commented
@PGLongo Can you rebase this pull request to get rid of the merge commit? Thank you.

2021-01-15 09:11 UTC, PGLongo commented
@fabpot rebase done

2021-01-15 10:37 UTC, OskarStark commented on symfony/gatewayapi-notifier/5.3/manifest.json
> +        "#1": "GATEWAYAPI_DSN=gatewayapi://TOKEN@default?from=SENDER"
```suggestion
        "#1": "GATEWAYAPI_DSN=gatewayapi://TOKEN@default?from=FROM"
```

To stay consistent with the README

2021-01-29 13:53 UTC, fabpot approved these changes

2021-01-29 13:53 UTC, merged