add recipe for amazon-notifier
symfony/recipes pull request #847
Opened 2020-11-22 21:32 UTC by adrien-chinour

| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | WIP

Hi, this PR is linked with symfony/symfony#39141

2021-07-10 09:12 UTC, nicolas-grekas commented
(please rebase so that the new checks can run)

2021-07-12 06:06 UTC, OskarStark requested changes

2021-07-12 06:06 UTC, OskarStark commented on symfony/amazon-sns-notifier/5.4/manifest.json
> +        "#1": "TEXTER_DSN=sns://ACCESS_KEY:SECRET_KEY@default?region=REGION"
```suggestion
        "#1": "AMAZON_SNS_DSN=sns://ACCESS_KEY:SECRET_KEY@default?region=REGION"
```

2021-07-13 07:42 UTC, OskarStark approved these changes

2021-07-27 04:53 UTC, merged