Add recipe for SpotHit Notifier bridge
symfony/recipes pull request #881
Opened 2021-01-23 00:51 UTC by JamesHemery

| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | symfony/symfony-docs#14869

2021-01-24 08:39 UTC, OskarStark requested changes

2021-01-24 08:39 UTC, OskarStark commented on symfony/spot-hit-notifier/5.3/manifest.json
> +        "#1": "SPOTHIT_DSN=spothit://api_token@default?from=MyCompany"
```suggestion
        "#1": "SPOTHIT_DSN=spothit://TOKEN@default?from=FROM"
```

2021-01-25 13:08 UTC, OskarStark approved these changes

2021-02-02 08:54 UTC, OskarStark commented on symfony/spot-hit-notifier/5.3/manifest.json
> +{
Please rename the folder to `spothit-notifier`

2021-02-02 18:24 UTC, OskarStark approved these changes

2021-02-14 17:45 UTC, fabpot commented
@symfony-flex-server review again please

2021-02-14 17:51 UTC, fabpot commented
@symfony-flex-server review again please

2021-02-14 18:01 UTC, fabpot commented
@symfony-flex-server review again please

2021-02-14 18:03 UTC, fabpot commented
Can you rename the directory to `spot-hit-notifier`?

2021-02-15 05:36 UTC, OskarStark approved these changes

2021-02-15 06:58 UTC, fabpot approved these changes

2021-02-15 06:58 UTC, merged