symfony/phpunit-bridge: set umask(0000) when debug is true
symfony/recipes pull request #889
Opened 2021-02-05 13:52 UTC by fancyweb

| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | -

When running functional tests with an empty cache (no directory), the cache directory is created. I run my tests with `APP_DEBUG=1`. I expect the cache directory to be created with the same permissions whether it is created from the tests or from a real request on the front controller. Currently, running the tests and then accessing the application lead to unexpected permissions errors.

Ref https://github.com/symfony/recipes/pull/210

2021-02-05 16:04 UTC, nicolas-grekas commented on symfony/phpunit-bridge/3.3/tests/bootstrap.php
> +}
missing EOL

2021-02-05 16:15 UTC, nicolas-grekas approved these changes

2021-07-10 09:10 UTC, nicolas-grekas commented
(please rebase so that we can run the new checks)

2021-07-12 13:27 UTC, nicolas-grekas commented
This should target the recipe for 5.3 IMHO.

2021-07-12 13:29 UTC, nicolas-grekas commented
At least, since we don't use symlinks anymore, this should update the latest of each major.

2022-02-17 15:45 UTC, nicolas-grekas commented
Friendly ping @fancyweb

2022-12-31 12:09 UTC, fabpot requested changes

2022-12-31 12:09 UTC, fabpot commented on symfony/phpunit-bridge/4.1/tests/bootstrap.php
> +}
missing EOL (and in some other files as well)

2023-01-02 08:28 UTC, fabpot approved these changes

2023-01-02 08:28 UTC, merged