[framework-bundle/5.3] Merge per-env settings
symfony/recipes pull request #902
Opened 2021-02-22 13:43 UTC by nicolas-grekas

| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | -

Leverages https://github.com/symfony/symfony/pull/40214

2021-02-24 07:23 UTC, jrushlow requested changes

2021-02-24 07:23 UTC, jrushlow commented on symfony/framework-bundle/5.3/config/packages/framework.yaml
> +            storage_factory_id: session.storage.mock_file
```suggestion
            storage_factory_id: session.storage.factory.mock_file
```

2021-02-24 07:24 UTC, jrushlow commented on symfony/framework-bundle/5.3/config/packages/framework.yaml
> +            storage_factory_id: session.storage.mock_file
as done in #905

2021-03-23 16:51 UTC, nicolas-grekas commented on symfony/framework-bundle/5.3/config/packages/framework.yaml
> +            storage_factory_id: session.storage.mock_file
thanks, updated.

2021-03-23 17:13 UTC, ogizanagi approved these changes

2021-04-05 18:38 UTC, jrushlow approved these changes

2021-04-05 22:38 UTC, yceruto approved these changes

2021-04-05 22:38 UTC, merged