[Doctrine Migrations] Enable new profiler by default in development
symfony/recipes pull request #927
Opened 2021-04-05 14:16 UTC by chr-hertel

| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | https://github.com/doctrine/DoctrineMigrationsBundle/pull/407    

Will be updated after release of doctrine migrations 3.1

2021-04-05 21:16 UTC, derrabus approved these changes

2021-04-06 20:26 UTC, xabbuh requested changes
LGTM

2021-04-06 20:27 UTC, wouterj commented
I'm getting a bit mixed feelings with your review, @xabbuh :smile:

2021-04-06 20:27 UTC, dbrumann approved these changes

2021-04-06 20:27 UTC, xabbuh approved these changes
wrong button

2021-04-06 20:28 UTC, merged